# Generated by Django 5.2.13 on 2026-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(default='NIU', max_length=10, verbose_name='Unidad de Medida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('afecto_igv', models.BooleanField(default=True, verbose_name='Afecto IGV')),
                ('cod_tipo_afectacion', models.CharField(default='10', max_length=10, verbose_name='Tipo de Afectación IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
    ]
