# Generated by Django 6.0.4 on 2026-04-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo_sunat', models.CharField(blank=True, max_length=10, verbose_name='Código SUNAT')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_operacion',
            field=models.CharField(choices=[('GRAVADA', 'Operación Gravada'), ('EXONERADA', 'Operación Exonerada'), ('INAFECTA', 'Operación Inafecta'), ('GRATUITA', 'Operación Gratuita'), ('EXPORTACION', 'Exportación')], default='GRAVADA', max_length=20, verbose_name='Tipo de Operación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto', verbose_name='Categoría'),
        ),
    ]
