# Generated by Django 6.0.4 on 2026-04-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoriaproducto_producto_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
    ]
