# Generated by Django 6.0.4 on 2026-04-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
