# Generated by Django 6.0.7 on 2026-07-16 07:42

from django.db import migrations, models


def normalizar_afectacion(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    Producto.objects.filter(cod_tipo_afectacion__in=['10', '17']).update(
        afecto_igv=True, tipo_operacion='GRAVADA'
    )
    Producto.objects.filter(cod_tipo_afectacion='20').update(
        afecto_igv=False, tipo_operacion='EXONERADA'
    )
    Producto.objects.filter(cod_tipo_afectacion='30').update(
        afecto_igv=False, tipo_operacion='INAFECTA'
    )
    Producto.objects.filter(cod_tipo_afectacion='40').update(
        afecto_igv=False, tipo_operacion='EXPORTACION'
    )
    Producto.objects.filter(
        cod_tipo_afectacion__in=[
            '11', '12', '13', '14', '15', '16', '21',
            '31', '32', '33', '34', '35', '36', '37',
        ]
    ).update(afecto_igv=False, tipo_operacion='GRATUITA')


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_updated_at_categoriaproducto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_tipo_afectacion',
            field=models.CharField(choices=[('10', '10 - Gravado - Operacion onerosa'), ('11', '11 - Gravado - Retiro por premio'), ('12', '12 - Gravado - Retiro por donacion'), ('13', '13 - Gravado - Retiro'), ('14', '14 - Gravado - Retiro por publicidad'), ('15', '15 - Gravado - Bonificaciones'), ('16', '16 - Gravado - Retiro por entrega a trabajadores'), ('17', '17 - Gravado - IVAP'), ('20', '20 - Exonerado - Operacion onerosa'), ('21', '21 - Exonerado - Transferencia gratuita'), ('30', '30 - Inafecto - Operacion onerosa'), ('31', '31 - Inafecto - Retiro por bonificacion'), ('32', '32 - Inafecto - Retiro'), ('33', '33 - Inafecto - Retiro por muestras medicas'), ('34', '34 - Inafecto - Retiro por convenio colectivo'), ('35', '35 - Inafecto - Retiro por premio'), ('36', '36 - Inafecto - Retiro por publicidad'), ('37', '37 - Inafecto - Transferencia gratuita'), ('40', '40 - Exportacion de bienes o servicios')], default='10', max_length=2, verbose_name='Tipo de Afectación IGV'),
        ),
        migrations.RunPython(normalizar_afectacion, migrations.RunPython.noop),
    ]
