# Generated by Django 5.2.13 on 2026-04-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('tipo_nota', models.CharField(choices=[('01', 'Anulación de la operación'), ('02', 'Anulación por error en el RUC'), ('03', 'Corrección por error en la descripción'), ('04', 'Descuento global'), ('05', 'Descuento por ítem'), ('06', 'Devolución por ítem'), ('07', 'Devolución total'), ('08', 'Bonificación'), ('09', 'Disminución del valor'), ('10', 'Otros')], max_length=2)),
                ('monto_afectado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprobante_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='comprobantes.comprobante')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
