# Generated by Django 5.2.14 on 2026-05-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_credito', '0001_initial'),
        ('productos', '0004_categoriaproducto_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacredito',
            name='monto_afectado',
        ),
        migrations.AddField(
            model_name='notacredito',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='op_gravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipo_nc',
            field=models.CharField(choices=[('NC', 'Nota de Crédito'), ('NCD', 'Nota de Crédito por Descuento')], default='NC', max_length=3),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='serie',
            field=models.CharField(default='FC01', max_length=4),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_nota',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('afecto_igv', models.BooleanField(default=True)),
                ('cod_tipo_afectacion', models.CharField(default='10', max_length=10)),
                ('igv_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_credito.notacredito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Nota de Crédito',
            },
        ),
    ]
