# Generated by Django 6.0.7 on 2026-07-14 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_credito', '0002_remove_notacredito_monto_afectado_notacredito_igv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacredito',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Nota de Crédito', 'verbose_name_plural': 'Notas de Crédito'},
        ),
        migrations.RenameField(
            model_name='notacredito',
            old_name='updated_at',
            new_name='actualizado_en',
        ),
        migrations.RenameField(
            model_name='notacredito',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
