# Generated by Django 6.0.7 on 2026-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_credito', '0003_alter_notacredito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='cdr_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='mensaje_sunat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='sunat_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='xml_firmado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
