# Generated by Django 5.2.13 on 2026-04-18 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC'), ('4', 'Carnet de Extranjería'), ('7', 'Pasaporte'), ('A', 'Cédula de Identidad')], default='6', max_length=2)),
                ('num_doc', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$')])),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social/Nombre')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
                'unique_together': {('tipo_doc', 'num_doc')},
            },
        ),
    ]
