# Generated by Django 6.0.4 on 2026-05-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision_documentos', models.DateField()),
                ('total_documentos', models.PositiveIntegerField(default=0)),
                ('enviandos', models.PositiveIntegerField(default=0)),
                ('aceptados', models.PositiveIntegerField(default=0)),
                ('rechazados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('ticket_ose', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_envio', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lote de Envío',
                'verbose_name_plural': 'Lotes de Envío',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
