# Generated by Django 6.0.7 on 2026-07-14 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_ose', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteenvio',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Lote de Envío', 'verbose_name_plural': 'Lotes de Envío'},
        ),
        migrations.RenameField(
            model_name='loteenvio',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='loteenvio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='loteenvio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loteenvio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
