# Generated by Django 5.2.14 on 2026-05-20 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('certificado_binario', models.BinaryField(verbose_name='Certificado (.pfx)')),
                ('contrasena', models.BinaryField(verbose_name='Contrasena (cifrada)')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Numero de Serie')),
                ('fecha_desde', models.DateField(verbose_name='Valido desde')),
                ('fecha_hasta', models.DateField(verbose_name='Valido hasta')),
                ('huella_digital', models.CharField(max_length=64, verbose_name='Huella Digital (SHA256)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-is_active', '-fecha_hasta'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('empresa',), name='unique_active_cert_per_empresa')],
            },
        ),
    ]
