"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

NOTA: Este archivo es un fallback. En Docker se usa config.settings.production.
En local se usa config.settings.local (via config/settings/__init__.py).
"""

# Importar desde el paquete settings (base + local por defecto)
from config.settings.base import *  # noqa: F401,F403

try:
    from config.settings.local import *  # noqa: F401,F403
except ImportError:
    pass
