# Generated by Django 5.2.13 on 2026-04-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], max_length=2)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ANULADO_PARCIAL', 'Anulado Parcial'), ('ANULADO_TOTAL', 'Anulado Total')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('zip_path', models.CharField(blank=True, max_length=500, null=True)),
                ('sunat_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('afecto_igv', models.BooleanField(default=True)),
                ('cod_tipo_afectacion', models.CharField(default='10', max_length=10)),
                ('igv_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
            },
        ),
        migrations.CreateModel(
            name='LogEnvioSUNAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_respuesta', models.CharField(max_length=20)),
                ('codigo_respuesta', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('cdr_xml', models.TextField(blank=True, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comprobantes.comprobante')),
            ],
            options={
                'verbose_name': 'Log de Envío SUNAT',
                'verbose_name_plural': 'Logs de Envío SUNAT',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo_actual', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobantes',
                'ordering': ['empresa', 'tipo', 'serie'],
                'unique_together': {('empresa', 'tipo', 'serie')},
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comprobantes.seriecomprobante'),
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('serie', 'numero')},
        ),
    ]
