# Generated by Django 6.0.4 on 2026-04-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_csv', models.FileField(upload_to='importaciones/')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('importados_exitosos', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PROCESANDO', max_length=20)),
                ('log_errores', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Comprobante',
                'verbose_name_plural': 'Importaciones de Comprobantes',
                'ordering': ['-fecha_importacion'],
            },
        ),
    ]
